# version: '3.8'
services:

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB: mydb
      DBUSER: myuser
      DBPASS: mypass
      DBHOST: postgres
      DBPORT: 5432
    # depends_on:
    #   - postgres
    networks:
      mynetwork:
        aliases:
          - api-app
  
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_HOST: "http://api:8080"
    networks:
      mynetwork:
        aliases:
          - web-app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'mypass'
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        aliases:
          - db-internal

networks:
  mynetwork:
    driver: bridge
